### ISSUE TITLE
[Tracker] Controller Unit Tests

### ISSUE THREAD

**Issue by BrenekH** [BrenekH/encodarr#119]
## Purpose
This issue is for tracking the progress of writing unit tests for the Controller, which is mostly taking place on the `controller-unit-tests` branch.

## Contributions
I'm happy to take pull requests which helps further this issue along, but be aware that I may request changes to better fit the project as I would any other PR.

Some important things to keep in mind:
 * Dependencies must be mocked (dependencies in this case simply means anything that is not easily controllable in a test)
     * Rewriting existing Controller code to support the mocking of dependencies is perfectly acceptable and in fact highly encouraged.
 * Tests should be independent of one another. This means that shared structs should not be used and instead a new one should be allocated for each test.

## Coverage
**Total Coverage:** 68.7%
  - [ ] jobhealth
    - [x] job_health.go - 100.0%
    - [x] mock.go - 80.0%
    - [x] structs.go - 0.0%
  - [ ] library
    - [ ] commanddecider
      - [ ] cmd_decider.go - 79.5%
    - [ ] cache.go - 59.3%
    - [ ] file_discovery.go - 45.8%
    - [ ] manager.go - 0.0%
  - [ ] settings
    - [x] mock.go - 92.9%
    - [ ] settings.go - 50.0%
  - [ ] sqlite
    - [ ] database.go - 0.0%
    - [ ] file_cache.go - 0.0%
    - [ ] health_checker - 0.0%
    - [ ] library_manager - 0.0%
    - [ ] runner_comm.go - 0.0%
    - [ ] user_interfacer.go - 0.0%
  - [x] mocks.go - 100.0%
  - [ ] run.go - 96.7%
  - [ ] structs.go - 0.0%
  - [x] util.go - 100.0%
